global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@ddos-inspector.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://httpbin.org/post'
    send_resolved: true

inhibit_rules: []