name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check committer
        run: |
          echo "🚫 Pushing directly to main is not allowed!"
          exit 1
