name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpcap-dev \
                                   libboost-all-dev snort3

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. 
          make -j$(nproc)

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Lint (clang-tidy)
        run: |
          cd build
          run-clang-tidy
